### ISSUE TITLE
reveal  transaction

### ISSUE THREAD

**Issue by lijianl** [Cryptonomic/ConseilJS#397]
when sending xtz, the API contains two kinds of transaction, one is reveal, another one is transaction

what is reveal  for

**Comment by anonymoussprocket** [comment]
on tezos, the first operation for an account is a public key reveal with records the public key on chain. this happens only once in general.

however if you drain you account to 0 and then attempt to use it again some time later, you'll end up issuing another reveal operation because empty EOAs are pruned.
